### ISSUE TITLE
Memory Warnings & Status Bar Bug

### ISSUE THREAD

**Issue by VictorAlexander** [kirbyt/KTPhotoBrowser#11]
While testing your code [flickr image sample] in my project, I've noticed that if you double tap or quickly tap a thumbnail, once the view comes up, there's a small delay and the console tells me it's a memory warning level 1 and sometimes level 2. The device is an iPhone 4. Any suggestions on what can be causing this, the large images aren't very large (640*400) mainly.

As for the status bar, if you mess around with the photoviewer, pinch in, pinch out, swipe past photos, hide the tab bar and such, there's a bug that randomly destroys the status bar and pushing the tab bar to the top of the screen.

**Comment by kirbyt** [comment]
This is a dup of Issue 10. Closing this one.
