### ISSUE TITLE
Retina Display

### ISSUE THREAD

**Issue by VictorAlexander** [kirbyt/KTPhotoBrowser#12]
I have no problem fixing up the arrows for retina display, but is there anyway I can fix the thumbnails to look perfect for retina display?

**Comment by VictorAlexander** [comment]
I have the same question... the default photo browser does implement this, so I'm assuming it's not impossible.

**Comment by kirbyt** [comment]
The data source (KTPhotoBrowserDataSource) provides the thumbnail. KTPhotoBrowser doesn't do any resizing what so ever. So the data source needs to provide a retina display version of the thumbnail, for instance, 150x150. 

FYI: 150x150 comes from the fact that the default thumbnail size is 75x75. The thumbnail size can be override in the thumbSize method of the data source. Also note the thumbNail is based on points, not pixels for iPhone 4. So the retina display thumbnail image should be double the size of the thumbSize.

Hope that helps.
