### ISSUE TITLE
Rotation from Landscape to Portrait

### ISSUE THREAD

**Issue by kyledecot** [kirbyt/KTPhotoBrowser#14]
When rotating from landscape to portrait on the photo scroll view, the animation is messed up.

**Comment by kirbyt** [comment]
I believe the problem is not related to rotating form landscape to portrait but rather rotating the last photo. At least that's what I'm able to reproduce. I'll looking into providing a fix soon.

**Comment by kirbyt** [comment]
This should now be fixed.  Sorry for the delay.  

-KIRBY
