### ISSUE TITLE
Zoomed in Mode

### ISSUE THREAD

**Issue by kyledecot** [kirbyt/KTPhotoBrowser#16]
When in zoomed in mode, the scrollview has black space on the left and right sides of the image. It seems like it should recalculate the area so that the image takes up the entire scrollview

**Comment by kyledecot** [comment]
Should be noted that the space is also on the top/bottom if you're in portrait mode

**Comment by kirbyt** [comment]
If I'm not mistaken, the Photo.app has the same left and right separator space even when zoomed in. This can be changed by adjusting the content offset in the file KTPhotoScrollViewController.m. The current implementation uses an offset of 20 as defined by CONTENT_OFFSET (in the same file).
