### ISSUE TITLE
Asynchronous Image

### ISSUE THREAD

**Issue by kyledecot** [kirbyt/KTPhotoBrowser#17]
If you are using asynchronous images and are in KTPhotoScrollView, the first image will load & display correctly. Then if you move forward or backwards a couple of images, the first image will be displayed in place of the correct image until the correct image has loaded. It will then be swapped for the correct one.

**Comment by kirbyt** [comment]
The scroll view has been rewritten. The problem should now be fixed. Please test and let me know if you are still able to reproduce the problem. 

Thanks,
-KIRBY
