### ISSUE TITLE
iPad Landscape Mode UIScrollView jumps to index 0

### ISSUE THREAD

**Issue by WrightsCS** [kirbyt/KTPhotoBrowser#20]
For some reason, this happens only when going into Photo View while already in Landscape, and only on the iPad.

Say you tap on Image 50(index 50), the scrollview loads image 50, but when you tap anywhere on the screen, it jumps to index 0! 

Also, same scenario, you cant scroll past index 39? Which is a contentSize issue because I have tried other values. But theres no explanation why this is happening. Portrait mode works perfectly. Also, when switching to landscape in Photo View from Portrait, the view is fine, no issues.

Anyone else experience this crazy issue?

**Comment by kirbyt** [comment]
The problem was caused by an incorrect content size on the scroll view after rotation. I fixed this along with other rotation related issues.

Thanks for reporting the problem.

-KIRBY
