### ISSUE TITLE
setDatasource

### ISSUE THREAD

**Issue by alpertayfun** [kirbyt/KTPhotoBrowser#22]
/Users/alpertayfun/Documents/Sample/Classes/SampleViewController.m:24:0 /Users/alpertayfun/Documents/Sample/Classes/SampleViewController.m:24: warning: 'SampleViewController' may not respond to '-setDataSource:'

[self setDataSource:[self data]];

How can i fix it ?

**Comment by kirbyt** [comment]
Looks like you have not declared setDataSource: in the @interface. If you post the SampleViewController.h and .m code I might be able to give you a better answer.

-KIRBY
