### ISSUE TITLE
Navigation Bar doesn't become Transparent

### ISSUE THREAD

**Issue by kyledecot** [kirbyt/KTPhotoBrowser#3]
While testing on iPhone 4.0 the navigation bar does not become transparent and is also positioned in the incorrect position. Please see link of photo below for example:

http://i724.photobucket.com/albums/ww247/affinityskateboards/IMG_0342.png

**Comment by kirbyt** [comment]
I'll look into the problem, but can't guarantee a fix for 4.0 until the release. This is assuming the fix requires something 4.0 related and under NDA at the moment.
