### ISSUE TITLE
Xcode 4.2 ARC Support

### ISSUE THREAD

**Issue by guilhermebattaglin** [kirbyt/KTPhotoBrowser#35]
Hi, 

how can I get KTPhotoBrowser to work with Xcode 4.2 ARC?

**Comment by kirbyt** [comment]
I haven't had time to work this project recently.  I hope that changes in the near future.  Until such time...

The code needs to be updated to support ARC or you can use the -fno-objc-arc flag on each file. This flag is set under the Build Phases > Compile Sources for the target.

-KIRBY

**Comment by guilhermebattaglin** [comment]
Thanks Kirby,

It works fine!
