### ISSUE TITLE
update data source

### ISSUE THREAD

**Issue by rogowskimark** [kirbyt/KTPhotoBrowser#40]
I have implemented KTPhotoBrowser into my project. I am using Core Data to store paths for images which are saved in NSHomeDirecotry. What I need to do is give ability to user to delete photos. That I have figured out how to manage data base and files, but I have got problem with PhotoDataSource. It do not know how to update it. I have got reference to it in view controller, but that does not get changed. I would would like to do it in viewWillAppear method each time it gets called. Please advise me how to solve it.

**Comment by kirbyt** [comment]
In your data source object, implement the optional method -deleteImageAtIndex: from the KTPhotoBrowserDataSource protocol. This tells the data source which photo should be removed. The implementation should remove the path from Core Data and the image from the file system.

Hope that helps.
-KIRBY
