### ISSUE TITLE
using 2 datasource for thumbnails and bigsize images

### ISSUE THREAD

**Issue by elephantman** [kirbyt/KTPhotoBrowser#45]
hi

i want to use use 2 different datasource for the thumbnails and the big size images. because of the big size images are too heavy the loading time is longer so i need to create another array or dictionary for the thumbs and when user click a thumb in the big size window another datasource should be called.

is it possible with your project? how? or please suggest another advice for my problem

thanks

**Comment by kirbyt** [comment]
-imageAtIndex: can be implemented to retrieve the image from a different source than -thumbImageAtIndex:. No need to have two data source objects. 

-KIRBY

**Comment by elephantman** [comment]
ok i got it thank you that solves my problem
