### ISSUE TITLE
Can't switch to SDWebImageRootViewController

### ISSUE THREAD

**Issue by LuaiKalkatawi** [kirbyt/KTPhotoBrowser#64]
Hi, I have copied the KTPhotoBrowser and SDWebImageSample from the sample file to my project. Also I have created the navigation view with UIButton to pushViewController (ThumbnailView). I have called this code but nothing happen. Please I need help. Thanks.

SDWebImageRootViewController *newController = [[SDWebImageRootViewController alloc] init];
    [[self navigationController] pushViewController:newController animated:YES];
    [newController release];

**Comment by kirbyt** [comment]
This is typically caused when self is not contained in a navigation controller. 

-KIRBY

**Comment by LuaiKalkatawi** [comment]
Thanks... it is working.
