### ISSUE TITLE
ScrollViewController Display Problem

### ISSUE THREAD

**Issue by kyledecot** [kirbyt/KTPhotoBrowser#7]
When the ScrollViewController view get's pushed onto the stack no photo is visible. However if I rotate the device, the image appears. Also, when I tap next to go to the second photo, it displays correctly but if I tap next again, I see the first photo where the third one should be. If I then rotate the device, the third photo is updated w/ the correct image. This also happens when going backwards w/ the previous button.

**Comment by kirbyt** [comment]
I rewrote how the scroller works. This problem should now be fixed. Please test and let me know if you are still experiencing problems.

Thanks,
-KIRBY
