### ISSUE TITLE
Rotation Does Not Reset Chrome Timer

### ISSUE THREAD

**Issue by kyledecot** [kirbyt/KTPhotoBrowser#8]
In the Apple Photos App when you have the chrome display visible and keep rotating the device every few seconds, the display will never fade out. This should be an easy fix.

**Comment by kyledecot** [comment]
I just added [self startChromeDisplayTimer]; to KTPhotoScrollViewController's didRotateFromInterfaceOrientation:

**Comment by kirbyt** [comment]
Thanks for reporting this and providing a fix. I added the fit to the main source. Sorry for the delay.
